apiVersion: v1
kind: Service
metadata:
  name: marketplacer-client-service
spec:
  selector:
    app: marketplacer-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
